### ISSUE TITLE
[milestone] Configs are validated and errors are shown in the UI

### ISSUE THREAD

**Issue by kmcq** [open-truss/open-truss#102]
## Summary

With the config's `zod` type system and `UQI`'s strongly typed queries, we can validate and show helpful errors to users while they're building and using workflows.

## Tasks

- [ ] https://github.com/open-truss/open-truss/issues/80
- [ ] https://github.com/open-truss/open-truss/issues/92
- [ ] Create an `<ErrorBoundary />` that replaces a failing frame with helpful error context
