### ISSUE TITLE
[Milestone] Config spec v0.0.2

### ISSUE THREAD

**Issue by hktouw** [open-truss/open-truss#112]
## Why

To support more complex workflows (e.g. multi-stage workflows, stored query backend, pagination through results), we need a more sophisticated version of the config spec.

## How

We will to implement the next version of the config spec as proposed in https://github.com/open-truss/open-truss/pull/111.

<details>

<summary>Example configuration</summary>

```yaml
# Worfklow name: Get all issues for a given user
# This is a multi-stage workflow
# 1. Show input form to add account_id
# 2. User inputs account_id
# 3. Shows list of issues belonging to that account_id
workflow:
  version: 1
  signals:
    - account_id: number
  renderFrames: InSequence
  frames:
    - frame:
      view:
        component: OTInputForm
        props:
          fields:
            - :account_id
    - frame:
      data:
        query: >\n
          SELECT id AS issue_id
          FROM issues
          WHERE author_id = :account_id
        params:
          account_id: :account_id
        transforms:
          mapColumns:
            issue_id: issue_ids # TableOfContent
        type: StoredQuery
        pageSize: 50
        source: mysql1
      frames:
        - frame:
          view:
            component: OTStoredQueryToolbar
        - frame:
          view:
            component: TableOfContent
              content_ids: :issue_ids # example of argument aliasing
              content_type: issue
```

</details>

### Tasks
- [x] Decide on first pass of config spec v0.0.2 https://github.com/open-truss/open-truss/pull/111
- [ ] Implement state management https://github.com/open-truss/open-truss/pull/110
- [ ] Implement renderFrames
- [ ] Implement navigation functions
- [ ] Implement data params
- [ ] Implement data transforms
- [ ] Implement StoredQueries
