### ISSUE TITLE
[Milestone] Config Builder v0.0.2

### ISSUE THREAD

**Issue by hktouw** [open-truss/open-truss#208]
## Why

Now that the core OT engine is in a usable alpha version, we can spend more time on the config buidler. We want config builder to support the new features of the rendering engine (e.g. signals), have better usability, and support raw css styling to make it easier to make an opinionated design while being importable to different applications.

## Todo

Below are a list of work items based on the [discussion](https://github.com/open-truss/open-truss/discussions/161) post @kmcq opened.
- [ ] Convert config builder to use css
- [ ] Add support for new rendering engine features (e.g. signals)
- [ ] Support exporting configs to paste buffer
- [ ] Support reordering frames
- [ ] Support ability to edit yaml directly
- [ ] Add documentation support for components
- [ ] Add ability to resize editor vs rendered windows
- [ ] Add ability to click into components and edit props directly

**Comment by jonmagic** [comment]
@hktouw do you still want this config builder milestone open?

I am doing a cleanup pass after #275, and this one still looks plausible because the config builder exists in the demo app. I do not know whether the v0.0.2 checklist still matches what you want, though.

If yes, I can leave it open and we can prune it down to the current config-builder work. If not, I think we can close it as stale and open smaller issues later if config-builder work comes back.
