### ISSUE TITLE
[Milestone :checkered_flag:] User Stories

### ISSUE THREAD

**Issue by hktouw** [open-truss/open-truss#4]
## Summary

In service of helping us be more user-centric and help guide development, we want to sketch out a few user stories.

## Overview

Open Truss is a tool for super users to build tools. We should be thinking of developing Open Truss from their perspective. To that end, we have the opportunity to sketch out user stories to help solidify our understanding of these users and how Open Truss might help them. Based on @jonmagic @kmcq @hktouw's experience from our day jobs and ability to work closely with these users, we are going to start with the following 3 user personas.

- Abuse security analyst
- Data scientist / content labeller
- First responder / Incident responder

### Problems this is trying to solve

Developing without some understanding of who we are building for and how Open Truss might help them

## Todo

- [ ] Data scientist / content labeller @kmcq
- [ ] First responder / Incident responder @jonmagic
- [ ] Abuse security analyst @hktouw

**Comment by jonmagic** [comment]
Closing this as stale planning after the repo focus work in #275.

The personas may still be useful context, but this 2023Q4 milestone no longer matches how the repo is being managed. If we want user stories again, I think we should open a smaller refreshed issue tied to the current package/demo/docs direction.
