### ISSUE TITLE
REST data provider

### ISSUE THREAD

**Issue by jonmagic** [open-truss/open-truss#41]
> Should this use uqi under the hood? The uqi source pattern to define the values needed to execute a query feels necessary (endpoint, creds) but unclear if the rest fits. REST != SQL and everything uqi does right now is SQL'ish or SQL adjacent.

Probably not. We'll try to implement this outside of uqi first. If there's enough overlap in the working implementation we'll migrate it to uqi.

## TODO

- [x] Sketch out yaml config for a rest call (w/ schema for endpoint responses)
- [x] Build `/api/synchronous-rest-call` server endpoint
- [x] Build non-uqi `OTRestDataProvider`
- [x] Implement feature to map JSON values from endpoint to a signal (e.g. object paths `.foo.bar[]`)
- [x] Implement signal injection into URL template string
- [x] Cleanup & write tests

**Comment by andrew-dillon** [comment]
@hktouw here's what I'm thinking for the yaml config:
```yaml
# Fetches and displays the total numbers of issues in the open-truss/open-truss repo
workflow:
  version: 1
  signals:
    results:
      total_count: string
  frames:
    - frame:
      view:
        component: OTRestDataProvider
        props:
          source: rest-demo
          path: /search/issues?q=repo:open-truss/open-truss+is:issue&per_page=1
          method: GET
          output: [:results]
          headers:
            - User-Agent: open-truss-rest-demo
      frames:
        - frame:
          view:
            component: DataDemo
            props:
              results: :results
```

The config for `source: rest-demo` will specify the protocol (e.g. `https`), auth headers (e.g. `Authorization: Bearer ...`), and the domain (e.g. `api.github.com`). 

It would be nice if we could parameterize the path, e.g.
```yaml
          path: /search/issues?q=repo:{repo_nwo}+is:issue&per_page={num_per_page}
```

I suppose the `OTRestDataProvider` could inject signals into the query string. What do you think?

**Comment by jonmagic** [comment]
> I suppose the `OTRestDataProvider` could inject signals into the query string. What do you think?

I dig it. Does it need to support pagination from day one? Should be fairly straightforward if you make the path prop a template that can be updated 👍

**Comment by andrew-dillon** [comment]
> a template that can be updated 👍

Can you expound on this? Do you have an example?

**Comment by jonmagic** [comment]
I was thinking you could use something like https://lodash.com/docs/4.17.15#template

**Comment by andrew-dillon** [comment]
Oh right. What values should OT inject? Do you think injecting signals to populate the template makes sense?

**Comment by jonmagic** [comment]
> Oh right. What values should OT inject? Do you think injecting signals to populate the template makes sense?

I think so. That seems to be the way we're handling state. It's nice because it makes it possible to update state used in one component from another component as long as the state is stored at a level high enough in the tree that both components have access to it.

**Comment by andrew-dillon** [comment]
Added a `synchronous-rest-query` endpoint in [this branch](https://github.com/open-truss/open-truss/compare/main...rest-data-provider). Working on a `OTRestDataProvider` component now.

**Comment by andrew-dillon** [comment]
Just pushed a commit implementing `<OTRestDataProvider />`. Going to work on URL string templating and tests next.

**Comment by hktouw** [comment]
Took a look at your branch. Fantastic progress so far. Looking good. 👍 

FYI, per the conversation in discord and this PR to make [Signals Nullable](https://github.com/open-truss/open-truss/pull/182), we are probably going to standardize on the convention for data providers of casting values if they are present and leaving them as null if they are null. That way, we avoid the ambiguity between a value that is not present and a zero value. e.g. `""` vs `null`. We'll likely want to do something similar with the reset provider.

**Comment by andrew-dillon** [comment]
Just finished the URL string templating. Since signals are globally accessible to components I had to resort to a `pathValues` object. If components could access signals via React Context then we could do away with `pathValues`. Instances of `<OTRestDataProvider />` could find template variable names in the path string and lookup the corresponding signal from the React Context.

**Comment by andrew-dillon** [comment]
The path templating makes pagination easy 🎉

**Comment by andrew-dillon** [comment]
It's finished at this point except for tests. I'll have a PR up soon once I'm done with tests. Feel free to leave early feedback here!
