### ISSUE TITLE
[Milestone 🏁] Alpha Release: Minimal, but Usable and Extendable

### ISSUE THREAD

**Issue by kmcq** [open-truss/open-truss#5]
## Summary
Everything's gotta start somewhere.

## Overview
Open Truss's alpha will see it being a minimal, but **usable** and **extendable** platform framework.

### Definition of done
* [x] OT is one or more installable NPM package(s).
* [x] Initial patterns and contracts are set for creating display components.
* [x] Display components can either be OSS or internal.
* [x] Initial configuration schema is defined and documented.
* [x] One query adapter is implemented as a data container/fetcher component.
* [x] Given a query (or a query template and variables) and a display configuration, data is displayed.
* [x] The example application has a working demo.
* [x] Add appropriate OSS license (MIT?)

## Todo
* [ ]  [Add here]

**Comment by kmcq** [comment]
@jonmagic @hktouw I just wanted to point out that this is almost done!

**Comment by hktouw** [comment]
I think we've pretty much shipped everything on this list. Going to close this issue out. Great work everyone!
