### ISSUE TITLE
[Batch] Query user interface and everything needed to support it

### ISSUE THREAD

**Issue by jonmagic** [open-truss/open-truss#66]
## Summary

We want a user interface for submitting queries and viewing query results. There are many parts that go into building this from backend endpoints to React hooks to components to open-truss configs.

Eventually this interface should be built using open-truss but it may take a bit of back and forth to get to that point. The important thing right now is getting query and result user interfaces (or a combined user interface) started so we can iterate and make them awesome.

This will also help drive backend development of more query sources (uqi clients for mysql, REST, etc).

## Tasks

- [x] GraphQL endpoint for UQI https://github.com/open-truss/open-truss/pull/65
- [x] REST endpoint for UQI https://github.com/open-truss/open-truss/pull/65
- [ ] React hooks for issuing queries
- [ ] Backend to store query results to support asynchronous queries
- [ ] Endpoints for stored queries
- [ ] Hooks for stored queries
- [ ] Query user interface

**Comment by jonmagic** [comment]
I think this can be closed.
