### ISSUE TITLE
[Milestone] Improve and showcase OT's usability with real examples

### ISSUE THREAD

**Issue by kmcq** [open-truss/open-truss#78]
Continuing on from https://github.com/open-truss/open-truss/issues/32, we can improve and showcase OT's usability by doing the following:

- [ ] #79
- [ ] config builder: improve UI (it's really ugly right now 😅).
- [ ] Add some layout components (e.g. `FlexBox`) and example configs that have things like two column layouts.
- [x] Add some example UQI components like one that takes in a Trino query as a prop and one that takes in a REST endpoint as a prop.

**Comment by hktouw** [comment]
@kmcq What do you think would be a good set of features to consider this milestone done?
